Implement `yarn lint --fix` and rework scripts.
## Why silent true?

Because it was hard to find the fix command suggestion in all the output.

```sh
% yarn lint      
yarn run v1.22.22
$ node bin/suggest-fixing-command.js lint-or-lint-fix-internal 'lint --fix'
$ node bin/lint-or-lint-fix.js
$ run-p lint-internal:**
$ node bin/format.js
$ eslint *.js bin src --report-unused-disable-directives --cache --cache-strategy content
$ stylelint "src/**/*.css" "res/**/*.css"
[warn] bin/format.js
[warn] Code style issues found in the above file. Run Prettier with --write to fix.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "lint-internal:format" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
💡 You might be able to fix the error by running `yarn lint --fix`
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Why format.js?

Because `prettier --check . --fix` doesn't work, it needs to be `prettier --write .`.

## Why so many commands?

Good question.

## What's the mapping of old commands to new commands?

TODO